# Generated by Django 5.2.16 on 2026-10-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beleg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("dateipfad", models.FileField(blank=True, upload_to="belege/%Y/%m/")),
                ("gesamtbetrag", models.DecimalField(decimal_places=2, max_digits=9)),
                ("haendler", models.CharField(blank=True, max_length=150)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Beleg",
                "verbose_name_plural": "Belege",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Getraenk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "warenpreis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Einkaufspreis pro Einheit (reiner Warenpreis ohne Pfand)",
                        max_digits=8,
                    ),
                ),
                ("verkaufspreis", models.DecimalField(decimal_places=2, max_digits=8)),
                ("aktiv", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Getränk",
                "verbose_name_plural": "Getränke",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Kassenbewegung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("einlage", "Einlage (Privateinlage)"),
                            ("entnahme", "Entnahme"),
                            ("fremder_bargeldeingang", "Fremder Bargeldeingang"),
                        ],
                        max_length=30,
                    ),
                ),
                ("datum", models.DateField()),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "rg_nummer",
                    models.CharField(
                        blank=True,
                        help_text="Nur bei 'Fremder Bargeldeingang': Verweis auf die Rechnungsnummer aus dem Rechnungsprogramm (keine Texterkennung in dieser Version – die Vertrauenskasse erstellt selbst keine Rechnungen und vergibt nur ihre eigenen VK-Nummern).",
                        max_length=50,
                    ),
                ),
                ("notiz", models.CharField(blank=True, max_length=255)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kassenbewegung",
                "verbose_name_plural": "Kassenbewegungen",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaypalStichwort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wort", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "PayPal-Stichwort",
                "verbose_name_plural": "PayPal-Stichwörter",
                "ordering": ["wort"],
            },
        ),
        migrations.CreateModel(
            name="Zaehlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("notiz", models.TextField(blank=True)),
                (
                    "belegnummer",
                    models.CharField(
                        blank=True,
                        help_text="Wird automatisch im Format VK-JJJJ-MM-NN vergeben.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "bargeld_gezaehlt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gezaehltes Bargeld in der Kasse bei dieser Zaehlung",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Zählung",
                "verbose_name_plural": "Zählungen",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Freigetraenk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("anzahl", models.PositiveIntegerField()),
                ("kommentar", models.CharField(blank=True, max_length=255)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "getraenk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="freigetraenke",
                        to="kasse.getraenk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freigetränk",
                "verbose_name_plural": "Freigetränke",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BelegPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anzahl", models.PositiveIntegerField()),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nur der Warenpreis laut Quittung, ohne Pfand-Anteil (Pfand steht auf der Quittung meist als eigene Zeile und wird nicht erfasst).",
                        max_digits=8,
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="kasse.beleg",
                    ),
                ),
                (
                    "getraenk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="belegpositionen",
                        to="kasse.getraenk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Belegposition",
                "verbose_name_plural": "Belegpositionen",
            },
        ),
        migrations.CreateModel(
            name="MonatsExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveIntegerField()),
                ("monat", models.PositiveSmallIntegerField()),
                ("exportiert_am", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Monatsexport",
                "verbose_name_plural": "Monatsexporte",
                "ordering": ["-jahr", "-monat"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("jahr", "monat"), name="unique_monat_export"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaypalZahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "verwendungszweck",
                    models.CharField(
                        blank=True,
                        help_text="Betreff/Verwendungszweck aus dem PayPal-Export, Basis der Auto-Zuordnung.",
                        max_length=255,
                    ),
                ),
                (
                    "ist_getraenke_zahlung",
                    models.BooleanField(
                        blank=True,
                        help_text="Ja/Nein = entschieden. Leer = ungeklaert (Klaerungsliste).",
                        null=True,
                    ),
                ),
                (
                    "zuordnungsgrund",
                    models.CharField(
                        blank=True,
                        help_text="Von der automatischen Zuordnung gesetzt oder manuell dokumentiert.",
                        max_length=255,
                    ),
                ),
                (
                    "paypal_transaktions_id",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "zaehlung",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wird beim monatlichen Abgleich anhand des Datums automatisch gesetzt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paypal_zahlungen",
                        to="kasse.zaehlung",
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal-Zahlung",
                "verbose_name_plural": "PayPal-Zahlungen",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ZaehlungVerbrauch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verbraucht",
                    models.PositiveIntegerField(
                        help_text="Wie viele wurden seit der letzten Zählung verkauft/verbraucht?"
                    ),
                ),
                (
                    "getraenk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verbraeuche",
                        to="kasse.getraenk",
                    ),
                ),
                (
                    "zaehlung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verbraeuche",
                        to="kasse.zaehlung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zählungsverbrauch",
                "verbose_name_plural": "Zählungsverbräuche",
                "ordering": ["zaehlung", "getraenk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zaehlung", "getraenk"), name="unique_zaehlung_getraenk"
                    )
                ],
            },
        ),
    ]
