# Generated by Django 5.2.16 on 2026-07-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beleg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("dateipfad", models.FileField(blank=True, upload_to="belege/%Y/%m/")),
                ("gesamtbetrag", models.DecimalField(decimal_places=2, max_digits=9)),
                ("haendler", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Getraenk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "warenpreis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Einkaufspreis pro Einheit",
                        max_digits=8,
                    ),
                ),
                (
                    "pfand",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("verkaufspreis", models.DecimalField(decimal_places=2, max_digits=8)),
                ("aktiv", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Zaehlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("notiz", models.TextField(blank=True)),
                (
                    "bargeld_gezaehlt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gezaehltes Bargeld in der Kasse bei dieser Zaehlung",
                        max_digits=9,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Freigetraenk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("anzahl", models.PositiveIntegerField()),
                ("kommentar", models.CharField(blank=True, max_length=255)),
                (
                    "getraenk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="freigetraenke",
                        to="kasse.getraenk",
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BelegPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anzahl", models.PositiveIntegerField()),
                ("einzelpreis", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="kasse.beleg",
                    ),
                ),
                (
                    "getraenk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="belegpositionen",
                        to="kasse.getraenk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaypalZahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "ist_getraenke_zahlung",
                    models.BooleanField(
                        default=False,
                        help_text="Nur als 'Getraenke-Zahlung' markierte Betraege fliessen in die Ist-Kasse ein",
                    ),
                ),
                (
                    "zaehlung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paypal_zahlungen",
                        to="kasse.zaehlung",
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ZaehlungBestand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vollbestand_gezaehlt", models.PositiveIntegerField()),
                ("leergut_gezaehlt", models.PositiveIntegerField()),
                (
                    "rueckgabe_an_getraenkemarkt",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Anzahl Leergut seit der letzten Zaehlung an den Getraenkemarkt zurueckgegeben",
                    ),
                ),
                (
                    "getraenk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bestaende",
                        to="kasse.getraenk",
                    ),
                ),
                (
                    "zaehlung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestaende",
                        to="kasse.zaehlung",
                    ),
                ),
            ],
            options={
                "ordering": ["zaehlung", "getraenk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zaehlung", "getraenk"), name="unique_zaehlung_getraenk"
                    )
                ],
            },
        ),
    ]
