# Generated by Django 5.2.16 on 2026-07-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kasse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beleg",
            options={
                "ordering": ["-datum", "-id"],
                "verbose_name": "Beleg",
                "verbose_name_plural": "Belege",
            },
        ),
        migrations.AlterModelOptions(
            name="belegposition",
            options={
                "verbose_name": "Belegposition",
                "verbose_name_plural": "Belegpositionen",
            },
        ),
        migrations.AlterModelOptions(
            name="freigetraenk",
            options={
                "ordering": ["-datum", "-id"],
                "verbose_name": "Freigetränk",
                "verbose_name_plural": "Freigetränke",
            },
        ),
        migrations.AlterModelOptions(
            name="getraenk",
            options={
                "ordering": ["name"],
                "verbose_name": "Getränk",
                "verbose_name_plural": "Getränke",
            },
        ),
        migrations.AlterModelOptions(
            name="paypalzahlung",
            options={
                "ordering": ["-datum", "-id"],
                "verbose_name": "PayPal-Zahlung",
                "verbose_name_plural": "PayPal-Zahlungen",
            },
        ),
        migrations.AlterModelOptions(
            name="zaehlung",
            options={
                "ordering": ["-datum", "-id"],
                "verbose_name": "Zählung",
                "verbose_name_plural": "Zählungen",
            },
        ),
        migrations.AlterModelOptions(
            name="zaehlungbestand",
            options={
                "ordering": ["zaehlung", "getraenk"],
                "verbose_name": "Zählungsbestand",
                "verbose_name_plural": "Zählungsbestände",
            },
        ),
    ]
