# Generated by Django 5.2.16 on 2026-07-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kasse", "0002_alter_beleg_options_alter_belegposition_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifferenzZuordnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("diebstahl", "Diebstahl"),
                            ("nicht_bezahlt", "Nicht bezahlt"),
                            ("freigetraenke", "Freigetränke (nicht erfasst)"),
                            ("veranstaltung", "Veranstaltung inkl. Getränke"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gleiches Vorzeichen wie die Kassendifferenz verwenden, z.B. -15.00 bei fehlendem Geld.",
                        max_digits=9,
                    ),
                ),
                ("kommentar", models.CharField(blank=True, max_length=255)),
                (
                    "zaehlung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differenz_zuordnungen",
                        to="kasse.zaehlung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Differenz-Zuordnung",
                "verbose_name_plural": "Differenz-Zuordnungen",
                "ordering": ["-zaehlung__datum", "kategorie"],
            },
        ),
    ]
