# Generated by Django 5.2.16 on 2026-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kasse", "0003_differenzzuordnung"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaehlung",
            name="bargeld_entnommen",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Wie viel von dem gezaehlten Bargeld direkt entnommen wurde (z.B. eingezahlt). 0 lassen, wenn das Geld in der Kasse bleibt.",
                max_digits=9,
            ),
        ),
    ]
