# Generated by Django 5.2.16 on 2026-07-14 11:25

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artikel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("beschreibung", models.TextField(blank=True)),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2, help_text="Netto-Einzelpreis", max_digits=8
                    ),
                ),
                (
                    "mwst_satz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        help_text="MwSt-Satz in Prozent, individuell je Artikel",
                        max_digits=5,
                    ),
                ),
                ("aktiv", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Firmenprofil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("adresse", models.TextField(blank=True)),
                ("steuernummer", models.CharField(blank=True, max_length=50)),
                ("ust_idnr", models.CharField(blank=True, max_length=50)),
                ("bank", models.CharField(blank=True, max_length=100)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("bic", models.CharField(blank=True, max_length=11)),
                ("logo", models.FileField(blank=True, upload_to="firma/")),
                (
                    "rechnung_fusszeile",
                    models.TextField(
                        blank=True,
                        help_text="Freitext am Ende jeder Rechnung/Quittung (z.B. Zahlungsziel)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firmenprofil",
                "verbose_name_plural": "Firmenprofil",
            },
        ),
        migrations.CreateModel(
            name="Gutschein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "typ",
                    models.CharField(
                        choices=[("fest", "Fester Betrag"), ("prozent", "Prozentual")],
                        default="fest",
                        max_length=10,
                    ),
                ),
                (
                    "wert",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Euro-Betrag bei 'Fester Betrag', Prozentsatz bei 'Prozentual'",
                        max_digits=8,
                    ),
                ),
                ("ausgestellt_am", models.DateField(default=datetime.date.today)),
                ("ablaufdatum", models.DateField(blank=True, null=True)),
                (
                    "grund",
                    models.CharField(
                        choices=[
                            ("verkauf", "Verkauf"),
                            ("preis", "Preis"),
                            ("verlosung", "Verlosungsgewinn"),
                        ],
                        default="verkauf",
                        max_length=10,
                    ),
                ),
                ("notiz", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-ausgestellt_am", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Konto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=100, unique=True)),
                ("iban", models.CharField(blank=True, max_length=34)),
                (
                    "kontonummer_datev",
                    models.CharField(
                        blank=True,
                        help_text="Kontonummer im DATEV-Kontenrahmen fuer den Export (z.B. Bankkonto)",
                        max_length=20,
                    ),
                ),
                ("aktiv", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["bezeichnung"],
            },
        ),
        migrations.CreateModel(
            name="Quittung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("datum", models.DateField(default=datetime.date.today)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional, Quittung kann auch ohne Namen ausgestellt werden",
                        max_length=200,
                    ),
                ),
                (
                    "verwendungszweck",
                    models.TextField(blank=True, help_text="Freier Verwendungszweck"),
                ),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=9)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quittungen",
                        to="buchhaltung.konto",
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Rechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("datum", models.DateField(default=datetime.date.today)),
                ("kunde_name", models.CharField(blank=True, max_length=200)),
                ("kunde_adresse", models.TextField(blank=True)),
                ("bezahlt", models.BooleanField(default=False)),
                ("bezahlt_am", models.DateField(blank=True, null=True)),
                ("notiz", models.TextField(blank=True)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rechnungen",
                        to="buchhaltung.konto",
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GutscheinEinloesung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(default=datetime.date.today)),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Eingeloester Euro-Wert bei dieser Buchung",
                        max_digits=8,
                    ),
                ),
                (
                    "gutschein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einloesungen",
                        to="buchhaltung.gutschein",
                    ),
                ),
                (
                    "quittung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gutschein_einloesungen",
                        to="buchhaltung.quittung",
                    ),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gutschein_einloesungen",
                        to="buchhaltung.rechnung",
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RechnungsPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=200)),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=8
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2, help_text="Netto-Einzelpreis", max_digits=8
                    ),
                ),
                ("mwst_satz", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "artikel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rechnungspositionen",
                        to="buchhaltung.artikel",
                    ),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="buchhaltung.rechnung",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ZahlungsdienstleisterGebuehr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anbieter",
                    models.CharField(
                        blank=True,
                        help_text="z.B. PayPal, SumUp, Stripe (Anbieter noch offen)",
                        max_length=100,
                    ),
                ),
                (
                    "bruttobetrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Voller eingegangener Betrag",
                        max_digits=9,
                    ),
                ),
                (
                    "gebuehr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Vom Anbieter einbehaltene Gebuehr",
                        max_digits=8,
                    ),
                ),
                ("datum", models.DateField(default=datetime.date.today)),
                (
                    "quittung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gebuehren",
                        to="buchhaltung.quittung",
                    ),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gebuehren",
                        to="buchhaltung.rechnung",
                    ),
                ),
            ],
            options={
                "ordering": ["-datum", "-id"],
            },
        ),
    ]
